/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.example.day01.actions.ComputeTotalDistanceBetweenLocationLists
import org.example.day01.infrastructure.LocationsRepository

fun main() {
    val reader = "3   4\n4   3".reader()
    val locations = LocationsRepository().getFromReader(reader)
    val distance = ComputeTotalDistanceBetweenLocationLists().execute(locations) 

    println("The total distance between locations is: $distance")
}
